#!/bin/ksh
#
# Copyright (C) 2019 rsiddharth <s@ricketyspace.net>
#
# SPDX-License-Identifier: ISC
#
#

daemon="/usr/local/virtualenv/.nfsw-prd/bin/uwsgi"
daemon_flags="--ini /etc/uwsgi/nfsw.ini"
daemon_user=_nfsw

export FLASK_APP=nfsw

. /etc/rc.d/rc.subr

rc_reload=NO

rc_cmd $1
